version: '3.9'
services:

  gw:
    image: "dapr_demo/gw:latest"
    build: 
      context: .
      dockerfile: envoy/Dockerfile
    # image: "envoyproxy/envoy-dev:latest"
    ports:
      - "9901:9901"
      - "5000:10000"
    networks:
      - dapr-demo
  gw-dapr:
    image: "daprio/daprd:1.8.4"
    network_mode: "service:gw"
    command: [
      "./daprd",
      "-app-id", "gw",
      "-app-port", "10000",
      "-components-path","/components",
      "-config", "/configuration/config.yaml"
    ]
    volumes:
      - "./components:/components"
      - "./configuration/:/configuration"
    depends_on:
      - gw

  rest-service:
    image: "dapr_demo/rest-service:latest"
    build: 
      context: .
      dockerfile: src/rest-service/Dockerfile
    ports:
      - "5101:80"
    networks:
      - dapr-demo
  rest-service-dapr:
    image: "daprio/daprd:1.8.4"
    network_mode: "service:rest-service"
    command: [
      "./daprd",
      "-app-id", "rest-service",
      "-app-port", "80",
      "-components-path","/components",
      "-config", "/configuration/config.yaml"
    ]
    volumes:
      - "./components:/components"
      - "./configuration/:/configuration"
    depends_on:
      - rest-service

  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - dapr-demo

  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
    networks:
      - dapr-demo 
networks:
  dapr-demo: